import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Sidebar from '@/components/Sidebar';
import TopNavbar from '@/components/TopNavbar';
import RightHeader from '@/components/RightHeader';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${inter.className} flex flex-col h-screen `}
            >
                {/* <TopNavbar></TopNavbar> */}
                <div className='flex items-start justify-between h-screen '>
                    <Sidebar></Sidebar>
                    {/* 임시로 padding left 를 준다. */}
                    <main className='grid w-full h-auto pl-[300px]'>
                        <RightHeader></RightHeader>
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}
